name: Selenium Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code             #permet d'accéder au code
        uses: actions/checkout@v4

      - name: Set up Python             #configurer python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies             #installation des dependencies tout ce qui est dans requirments
        run: pip install -r requirements.txt

      - name: Run tests                #lancer tt ce qui dans dossier tests
        run: pytest tests/ -v

      - name: Upload screenshots on failure            #si y'a une erreur enregistre le screenshots dans le dossier dedier a ca 
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: screenshots/